language: node_js
node_js:
  - '8'
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy:
  - npm run docs
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
